Warning: [blastn] Unavailable feature GNUTLS
Critical: [blastn] Unavailable feature GNUTLS
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#4000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#6000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (302.132) [blastn] SSOCK#8000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#10000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#12000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 118: stack is empty: write fault
Error: (302.132) [blastn] SSOCK#14000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#16000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#18000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 0: stack is empty: cannot close output stream
Error: (CIOException::eFlush) [blastn] COStreamBuffer::Flush: failed
Error: (CSerialException::eIoError) [blastn] byte 0: cannot close output stream
Error: (802.4) [blastn] Cannot close serializing output stream (CSerialException::eIoError) byte 0: cannot close output stream
Error: (302.132) [blastn] SSOCK#20000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#22000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#24000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 118: stack is empty: write fault
Error: (302.132) [blastn] SSOCK#26000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#28000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#30000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 0: stack is empty: cannot close output stream
Error: (CIOException::eFlush) [blastn] COStreamBuffer::Flush: failed
Error: (CSerialException::eIoError) [blastn] byte 0: cannot close output stream
Error: (802.4) [blastn] Cannot close serializing output stream (CSerialException::eIoError) byte 0: cannot close output stream
Error: (802.5) [blastn] CObjectOStream: error at byte 118: stack is empty: write fault
Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/blast_1537407096784/work/c++/src/serial/rpcbase.cpp", line 244: Error: ncbi::CRPCClient_Base::x_Ask() - Failed to receive reply after 3 tries

Warning: [blastn] Unavailable feature GNUTLS
Critical: [blastn] Unavailable feature GNUTLS
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#4000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#6000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (302.132) [blastn] SSOCK#8000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#10000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#12000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 118: stack is empty: write fault
Error: (302.132) [blastn] SSOCK#14000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#16000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#18000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 0: stack is empty: cannot close output stream
Error: (CIOException::eFlush) [blastn] COStreamBuffer::Flush: failed
Error: (CSerialException::eIoError) [blastn] byte 0: cannot close output stream
Error: (802.4) [blastn] Cannot close serializing output stream (CSerialException::eIoError) byte 0: cannot close output stream
Error: (302.132) [blastn] SSOCK#20000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#22000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#24000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 118: stack is empty: write fault
Error: (302.132) [blastn] SSOCK#26000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#28000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (302.132) [blastn] SSOCK#30000[5]@195.221.122.200:8080: [SOCK::CreateOnTop]  Failed to initialize secure session
Error: (303.7) [blastn] [URL_Connect; https://www.ncbi.nlm.nih.gov:443/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Failed to use connection: Not supported
Error: (307.1) [blastn] [HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu]  Too many failed attempts (3), giving up
Warning: (301.21) [blastn] [CONN_Flush(HTTP; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=blast4&address=soere-meb(127.0.1.1)&platform=x86_64-unknown-linux-gnu)]  Failed to flush: Not supported
Error: (308.5) [blastn] [blast4]  Service not found
Error: (315.2) [blastn] CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) [blastn] CObjectOStream: error at byte 0: stack is empty: cannot close output stream
Error: (CIOException::eFlush) [blastn] COStreamBuffer::Flush: failed
Error: (CSerialException::eIoError) [blastn] byte 0: cannot close output stream
Error: (802.4) [blastn] Cannot close serializing output stream (CSerialException::eIoError) byte 0: cannot close output stream
Error: (802.5) [blastn] CObjectOStream: error at byte 118: stack is empty: write fault
Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/blast_1537407096784/work/c++/src/serial/rpcbase.cpp", line 244: Error: ncbi::CRPCClient_Base::x_Ask() - Failed to receive reply after 3 tries

