Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	kmc
	1
Select jobs to execute...

[Thu Feb 25 15:42:15 2021]
rule kmc:
    input: test/splitFiles
    output: test/kmerCounting/kmc3
    log: test/kmerCounting/kmc3/log.txt
    jobid: 1

[Thu Feb 25 15:42:15 2021]
Error in rule kmc:
    jobid: 1
    output: test/kmerCounting/kmc3
    log: test/kmerCounting/kmc3/log.txt (check log file(s) for error message)

RuleException:
CalledProcessError in line 144 of /databis/wu/stage_m2/Snakefile:
Command 'set -euo pipefail;  /databis/wu/miniconda3/envs/snakemake/bin/python3.9 /databis/wu/stage_m2/.snakemake/scripts/tmp6t0s8ou4.kmc3.py' returned non-zero exit status 1.
  File "/databis/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/databis/wu/stage_m2/Snakefile", line 144, in __rule_kmc
  File "/databis/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/databis/wu/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/databis/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/databis/wu/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Removing output files of failed job kmc since they might be corrupted:
test/kmerCounting/kmc3
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /databis/wu/stage_m2/.snakemake/log/2021-02-25T154214.507448.snakemake.log
